BetBolao/Controllers/BolaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BetBolao.Compartilhado.Dao;
using BetBolao.Compartilhado.Models;
using BetBolao.Dao;
using BetBolao.Models;
using BetBolao.ViewModel;

namespace BetBolao.Controllers
{
    [Authorize]
    public class BolaoController : Controller
    {
        #region Variables
        private readonly Competicao _competicao = new Competicao();
        private readonly List<Competicao> _competicoes = new List<Competicao>();
        //private readonly List<DTOParticipantesBolao> _convites = new List<DtoConvitesPendentes>();
        private readonly DaoBolao _dao = new DaoBolao();
        private readonly DaoConvite _daoConvite = new DaoConvite();
        private readonly Bolao _bolao = new Bolao();
        private readonly List<Bolao> _boloes = new List<Bolao>();
        private readonly Usuarios _usuarios = new Usuarios();
        private readonly ConvitesBolao _convite = new ConvitesBolao();
        #endregion

        #region métodos GET
        // GET: Bolao
        public ActionResult CadastrarBolao()
        {
            ViewBag.idUsuario = (int)Session["id"];
            ViewBag.competicoes = _competicao.TranformaListaCompeticoesEmSelectList(_competicao.ListarCompeticoes(new List<Competicao>()));
            //ViewBag.competicoes =  TranformaListaCompeticoesEmSelectList(ViewBag.competicoes);
            return View();
        }
        public ActionResult ListarBoloesParticipante()
        {
            _boloes.AddRange(_bolao.SelecinarBoloesPartipantes((int)Session["id"]));
            //_boloes.AddRange(_dao.ListarBoloesParticipante((int)Session["id"]));
            return View(_boloes);

        }
        public ActionResult CadastrarApostas(int id)
        {
            ViewBag.id = id;
            return View(new JogosCompeticao().ListaJogosCompeticao(id));
        }
        public ActionResult ConvidarParticipantes(int idbolao, int idanfitriao)
        {
            var auth = new AutenticacaoSeguranca();
            if (auth.PermissaoAcessoConfidencialConvidarAmigos(idanfitriao, idbolao))
            {
                return View();
            }
            return View("_NaoAutorizado");
        }
        public ActionResult ConvitesPendentes()
        {
            var id = (int)@Session["id"];

            var _convites = new List<DtoConvitesPendentes>();
            _convites.AddRange(_convite.RetornarConvitesPorUsuariosId(id));
            return View(_convites);

        }
        public ActionResult AceitarConvite(int id)
        {
            _convite.AceitarConvite(id);
            return RedirectToAction("ConvitesPendentes");
        }
        public ActionResult RejeitarConvite(int id)
        {
            _convite.RejeitarConvite(id);
            return RedirectToAction("ConvitesPendentes");

        }
        public ActionResult SairBolao(int idbolao)
        {
            var idusuario = Convert.ToInt32(Session["id"].ToString());
            _bolao.SairBolao(idbolao, idusuario);
            return RedirectToAction("ListarBoloesParticipante");

        }

        public ActionResult ListarBolao(int id)
        {
            var autenticacao = new AutenticacaoSeguranca();
            var idUsuario = (int)Session["id"];
            if (autenticacao.PermissaoAcessoConfidencialBolao(idUsuario, id))
            {
                var participantesBolao = new ParticipantesBolao();
                return View(participantesBolao.ListarBoloesParticipantes(id));
            }
            return View("_NaoAutorizado");
        }

        #endregion

        #region métodos Post
        [HttpPost]
        public ActionResult CadastrarBolao(Bolao bolao)
        {
            if (ModelState.IsValid)
            {
                bolao.CadastrarBolao(bolao);
            }
            return RedirectToAction("ListarBoloesParticipante", bolao.UsuarioCriadorBolao);
        }

        [HttpPost]
        public ActionResult ConvidarParticipantes(ConvitesBolao convitesBolao)
        {
            if (ModelState.IsValid)
            {
                var daoUsuarios = new DaoUsuarios();
                if ((convitesBolao.IdConvidado = daoUsuarios.RetornarIdUsuarioPorEmail(convitesBolao.EmailConvidado)) !=
                    0)
                {
                    _daoConvite.CriarConvite(convitesBolao);

                    return RedirectToAction("ConvidarParticipantes", new { idbolao = convitesBolao.IdBolao, idanfitriao = convitesBolao.IdAnfitriao });
                }
                TempData["mensagem"] = ViewBag.mensagem = "O email informado não é correspondente a um usuário do sistema";
            }
            return View();
        }

        #endregion

        #region métodos private

        #endregion
    }
}

BetBolao/Controllers/ContaController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BetBolao.Compartilhado.Models;

namespace BetBolao.Controllers
{
    public class ContaController : Controller
    {

        //código funcional
        //[HttpPost]
        //public ActionResult LogOn (FormCollection f, string returnUrl)
        //{
        //    var usuario = new Usuarios {Senha = f["senha"], Email = f["email"]};

        //    //usuario.LogarUsuario(usuario);
        //    if (usuario.LogarUsuario(usuario))
        //    {
        //        System.Web.Security.FormsAuthentication.SetAuthCookie(usuario.Email, false);
        //        return Redirect("~/Home/Index");
        //    }
        //    return View();
        //}


        #region get
        public ActionResult LogOn()
        {
            ViewBag.mensagem = this.Page_Load();
            return View(ViewBag);
        }
        
        public ActionResult LogOff()
        {
            System.Web.Security.FormsAuthentication.SignOut();
            Session.Abandon();
            return Redirect("~/Home/Home");
        }
        #endregion

        #region post
        [HttpPost]
        public ActionResult LogOn(FormCollection f, string returnUrl)
        {
            var usuario = new Usuarios { Senha = f["senha"], Email = f["email"] };
            if (ModelState.IsValid)
            {
                //usuario.LogarUsuario(usuario);
                if (usuario.LogarUsuario(usuario))
                {
                    ManterLogIn(usuario);

                }
            }

            ModelState.AddModelError("", "O login ou senha estão incorretos, tente novamente!");
            return View();

        }
        #endregion

        #region protected

        protected string Page_Load()
        {
            //var lblSessionID = string.Format("Session id: {0}", Session.Count);
            var lblSessionID = string.Format("Session id: {0}", Session.SessionID);
            return lblSessionID;
        }

        protected void Armazenar(string conteudo)
        {
            Session["Conteudo"] = conteudo;
            ViewBag.Mensagem = "Conteúdo armazenado na sessão";

        }

        protected void Ler()
        {
            if (Session["Conteudo"] != null)
            {
                ViewBag.mensagem = String.Format("Conteúdo da Sessão: {0}", Session["Conteudo"].ToString());
            }
        }

        #endregion
        #region private
        private void ManterLogIn(Usuarios usuario)
        {

            ManterSessaoUsuario(usuario);

            FormsAuthentication.Initialize();
            var fat = new FormsAuthenticationTicket(1,
                usuario.Nome.ToString(),
                DateTime.Now,
                DateTime.Now.AddMinutes(14),
                false, "user", FormsAuthentication.FormsCookiePath);
            Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName,
                FormsAuthentication.Encrypt(fat)));
            Response.Redirect(FormsAuthentication.GetRedirectUrl(usuario.Nome.ToString(), false));

        }

        private void ManterSessaoUsuario(Usuarios usuario)
        {

            Session["nome"] = usuario.Nome;
            Session["perfil"] = usuario.Perfil;
            Session["email"] = usuario.Email;
            Session["senha"] = usuario.Senha;
            Session["id"] = usuario.Id;
            Session["dataNascimento"] = usuario.DataNascimento;
            Session["comentarios"] = usuario.Comentarios;
            Session["timeFavorito"] = usuario.TimeFavorito;
        }

#endregion
    }
}

BetBolao/Views/Shared/ErroAcesso.cshtml
@{
    ViewBag.Title = "Erro de Acesso";
}

<h2>Lamentamos...</h2>


<p>A página que você tentou acessar ou não existe ou então você não possui acesso!!!</p>

<p>Possíveis soluções</p>
<ul style="list-style-type: disc" class="error-letra">
    <li>Sessão expirada: por favor, logue novamente;</li>
    <li>Cache e cookies: aperte Ctrl + F5 no seu teclado para limpar os arquivos de cookies;</li>
</ul>

<br />
<br />
<p>O erro persiste mesmo após os passos anteriores?</p>
<ul>
    <li>Não se preocupe, estamos trabalhando para corrigir este problema;</li>
    <li>Temos uma equipe que analisa diáriamente os logs do servidor e resolverão este problema.</li>
</ul>


<div class="bug-oito-mil">
    <img width="50%" height="50%" src="~/Imagens/8mil.jpg" />
</div>

BetBolao/Views/Shared/_ApostarJogos.cshtml
@model BetBolao.Models.JogosCompeticao

@{
    ViewBag.Title = "Apostar Jogos";
    string idbolao = Request.Params["idbolao"];
     
}

<h2>Tabela Jogos Competicao</h2>

@using (Html.BeginForm("Apostar", "Apostas"))
{
    if (Model.TabelaJogos.Count > 0)
    {
        foreach (var item in Model.TabelaJogos)
        {
            {
                {
                    //var campoEnabled = "";
                    <ul class="list-inline">
                        <li>
                            <span class="circuferenciaNumerica-placarJogo">
                                <div>
                                    @Html.DisplayFor(modelItem => item.IdJogo)
                                    <input type="hidden" value="@item.IdJogo" name="idJogo" id="idJogo" />
                                </div>
                            </span>
                            <div class="placar-jogo">

                                <div class="placar-jogo-informacoes">
                                    <span>
                                        @item.DataJogo.ToString("f")
                                        @*@{
                                            //campoEnabled = "";
                                            if (DateTime.Now >= item.DataJogo.AddHours(+2))
                                            {
                                                //campoEnabled = "";
                                            }
                                            else
                                            {
                                                //campoEnabled = "disabled = disabled";
                                            }
                                        }*@
                                    </span>
                                </div>
                                <div class="placar-jogo-equipes">
                                    <span>
                                        @Html.DisplayFor(modelItem => item.IdCompeticao)

                                    </span>
                                    <span class="placar-jogo-equipes-item placar-jogo-equipes-mandante">
                                        @Html.DisplayFor(modelItem => item.NomeTimeMandante)
                                        @*@Html.DisplayFor(modelitem => item.IdTimeMandante)*@
                                    </span>
                                    <span class="placar-jogo-equipes-item placar-jogo-equipes-placar">
                                        <span @*class="placar-jogo-equipes-placar-mandante resultadoJogo"*@>
                                            @*@Html.DisplayFor(m=>m.ResultadoMandante)*@

                                            <input class="placar-jogo-equipes-placar-mandante resultadoJogo lacamentoPlacar " type="text" min="0" max="99" maxlength="2" pattern="^[0-9]" name="resultadoMandante" placeholder='@item.ResultadoMandante' id="txtLancarPlacar" />

                                        </span>

                                        <span>X</span>

                                        <span @*class="placar-jogo-equipes-placar-visitante resultadoJogo"*@>
                                            @*@Html.DisplayFor(m => m.ResultadoVisitante)*@

                                            <input type="text" class="placar-jogo-equipes-placar-visitante resultadoJogo lacamentoPlacar " min="0" max="99" maxlength="2" pattern="^[0-9]" name="resultadoVisitante" placeholder='@item.ResultadoVisitante' id="txtLancarPlacar"/>

                                        </span>
                                    </span>

                                    <span class="placar-jogo-equipes-item placar-jogo-equipes-visitante">
                                        @*@Html.DisplayFor(modelItem => item.IdTimeVisitante)*@
                                        @Html.DisplayFor(modelItem => item.NomeTimeVisitante)
                                    </span>
                                </div>
                                <div class="placar-jogo-informacoes-campeonato">
                                    <span>@Html.DisplayFor(modelItem => item.Competicao)</span>
                                </div>


                            </div>

                        </li>
                    </ul>
                }
            }
        }

        <input type="submit" value="Apostar Jogos" id="@idbolao" />

    }


    else
    {

        <h1 class="text text-danger">Aviso: Este campeonato não possui jogos cadastrados!</h1>
        @*@Url.Action("Cadastrar Jogos", "CadastrarJogosCompeticao", new {id = RouteData["id"]})*@
        @*@Html.ActionLink("Cadastrar Jogos", "CadastrarJogosCompeticao", new {@value = id})*@

    }
}

@* código vem de lançar placar jogos*@

BetBolao/Views/Shared/_Layout.cshtml
@using System.Runtime.InteropServices
@using System.Web.ModelBinding
<!DOCTYPE html>
<html @*class="total"*@>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/StylePersonalizado.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js" type="text/javascript"></script>

    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/modernizr-2.6.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-1.10.2.intellisense.js" type="text/javascript"></script>
    <script src="~/Scripts/ValidacaoPersonalizada.js"></script>
    <style type="text/css">
        .bs-example {
            margin: 0;
            padding: 0 0 15px;
        }
    </style>
</head>
<body>
    <div class="bs-example ">
        <nav role="navigation" class="navbar navbar-default ">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class=" navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="menuNavegavel navbar-toggle">
                    <span class="sr-only">Toggle</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BetBolão", "Home", "Home", null, new { @class = "bolao-brand " })
            </div>
            <!-- Collection of nav links and other content for toggling -->
            <div id="navbarCollapse" class=" collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        if (Session["perfil"].ToString() == "administrador")
                        {
                            <li>
                                @Html.ActionLink("Administração", "HomeAdministrativa", "Home", null, new { @class = "menuNavegavel1" })
                            </li>
                        }

                    }
                    <li>
                        @Html.ActionLink("Menu Principal", "HomeUsuario", "Home", null, new { @class = "menuNavegavel1" })
                    </li>
                    <li>@Html.ActionLink("Listar Bolões", "ListarBoloesParticipante", "Bolao", null, new { @class = "menuNavegavel1" })</li>
                    
                    <li><a href="#">novidades em breve...</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="menuNavegavel1">
                        @*<div id="divLogin" @*style="color: white; text-align: right; float: right">*@
                        @if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            <p class="texto-logar-login">bem vindo: @HttpContext.Current.User.Identity.Name, @Html.ActionLink("log off", "LogOff", "Conta") </p>

                        }
                        else
                        {
                            @Html.ActionLink("Logar", "LogOn", "Conta")
                        }
                        @*  </div>*@
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    @*meu navbar*@
    @*<div class="navbar navbar-inverse navbar-fixed-top header">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("BetBolão", "Home", "Home", null, new {@class = "navbar-brand letterpress"})
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#">teste 1</a></li>
                        <li><a href="#">teste 2</a></li>
                        <li><a href="#">teste 3</a></li>
                    </ul>
                    <div id="divLogin" style="color: white; text-align: right; float: right">
                        @if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            <span> Bem vindo: @HttpContext.Current.User.Identity.Name</span>
                            @Html.ActionLink("LogOff", "LogOff", "Conta")
                        }
                        else
                        {
                            @Html.ActionLink("Logar", "LogOn", "Conta")
                        }
                    </div>
                </div>
            </div
        </div>*@

    <p class="text-center alert-danger"> @TempData["mensagem"]</p>

    <div class="main">

        <div class="container body-content total">

            @RenderBody()

        </div>
    </div>
    @*<div id="rodape">
            <div>

                &copy; @DateTime.Now.Year | BetBolão - Desenvolvido por Thiago Henrique em ASP.NET MVC 4 Application como TCC para faculdade Anhanguera

            </div>
        </div>*@
</body>

</html>
@*@section scripts{
        <script>
            $(function () {
                $(".details").click(function () {
                    var id = $(this).attr("data-id");
                    $("#modal").load("Details?id=" + id, function() {
                        $("#modal").modal();
                    });
                });
                $(".cadastrar").click(function () {
                    var id = $(this).attr("data-id");
                    $("#modal").load("Edit?id=" + id, function() {
                        $("#modal").modal();
                    });
                });
            })
        </script>
    }*@

BetBolao/Views/Shared/_NaoAutorizado.cshtml
Você não tem acesso á esta página...

BetBolao/Views/Shared/_VisualiarCompeticoesDisponíveis.cshtml
@model IEnumerable<BetBolao.Models.Competicao>

@{
    ViewBag.Title = "Listar Competições";
}

<h2>Lista das competições disponíveis</h2>


@*<table class="table table-responsive table-striped" id="centerTable">*@
<table class="table " id="centerTable">
    <tr>
        <th>
            #
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeCompeticao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ano)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
    </tr>
    @{
        var i = 0;
    }
    @foreach (var item in Model)
    {
        i++;
        <tr>
            <td>
                <p class="circuferenciaNumerica">@i</p>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeCompeticao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
        </tr>
    }
</table>

BetBolao/Views/Shared/_cadastrarView.cshtml
<div class="modal-dialog">
    @model BetBolao.Models.Time

    @{
        ViewBag.Title = "Cadastrar";
    }


    @*<h2>Cadastrar Time</h2>*@

    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Cadastrar Time</h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm())
            {


                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Times</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.NomeTime, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NomeTime, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NomeTime, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.IdPais, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.IdPais, ViewBag.idPais as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdPais, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*<div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>*@


                </div>

            }
        </div>
        <div class="modal-footer">
            <input type="submit" value="Salvar" class="btn btn-primary" />
            <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
        @*<div>@Html.ActionLink("Voltar", "Index")</div>*@
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>