BetBolao/Models/bolao.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using BetBolao.Compartilhado.Dao;
using BetBolao.Dao;

namespace BetBolao.Models
{
    public class Bolao
    {
        private DaoBolao _dao = new DaoBolao();

        public Bolao()
        {
            
        }
        public Bolao(string participando)
        {
            Participando = participando;
        }

        [Required]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "O nome do bolão não pode ter menos que 4 caracteres ou ser maior que 50 caracteres.")]
        [Display(Name = "Nome do Bolao:")]
        public string NomeBolao { get; set; }
        
        public int Id { get; set; }
        //public string NomeCompeticao { get; set; }

        public int UsuarioCriadorBolao { get; set; }

        [Display(Name = "Campeonato Associado:")]
        public int IdCampeonatoAssociado { get; set; }

        private string Participando { get; set; } 


        #region metodos public

        public void CadastrarBolao(Bolao bolao)
        {
            _dao.CadastarBolao(bolao);
        }

        public List<Bolao> SelecinarBoloesPartipantes(int id)
        {
            var ListaCompleta = new List<Bolao>();
            var ListaFiltrada = new List<Bolao>();
            ListaCompleta.AddRange(_dao.ListarBoloesPorUsuarioParticipante(id));
            ListaFiltrada.AddRange(ListaCompleta.Where(x=> x.Participando!="não"));

            //var listaFiltrada = listaCompleta.Where(b => b.IdConvidado == idUsuario);

            return ListaFiltrada;

        }


        public void SairBolao(int idbolao, int idusuario)
        {
            _dao.AtualizarParticipacaoBolaoParaNao(idbolao, idusuario);
        }
        //public void ListarCompeticoesPorUsuarioCriador()
        //{
            
        //}


        #endregion
    }
}

BetBolao/Controllers/ApostasController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BetBolao.Compartilhado.Models;
using BetBolao.Models;

namespace BetBolao.Controllers
{
    [Authorize]
    public class ApostasController : Controller
    {
        #region private variables
        private readonly Aposta _aposta = new Aposta();
        #endregion

        #region  get
        // GET: Apostas/Create
        [HttpGet]
        public ActionResult Apostar(int idCompeticao, int idbolao)
        {
            var idUsuario = Convert.ToInt32(Session["id"]);
            var autorizacao = new AutenticacaoSeguranca();
            if (autorizacao.PermissaoAcessoConfidencialBolao(idUsuario, idbolao))
            {
                var jogos = new JogosCompeticao();
                jogos.ListaJogosCompeticaoSemanaAtual(idCompeticao, idUsuario, idbolao);
                return View(jogos);
            }
            return View("_NaoAutorizado");
        }

        #endregion get

        #region post
        [HttpPost]
        [Route(Name = "Apostar")]
        public ActionResult Apostar(string[] idJogo, int[] resultadoMandante, int[] resultadoVisitante, int idbolao)
        {
            try
            {
                var idUsuario = Convert.ToInt32(Session["id"]);
                var aposta = new Aposta();
                for (var i = 0; i < idJogo.Count(); i++)
                {
                    aposta.Jogo = Convert.ToInt32(idJogo[i]);
                    aposta.PlacarTimeMandante = Convert.ToInt32(resultadoMandante[i]);
                    aposta.PlacarTimeVisitante = Convert.ToInt32(resultadoVisitante[i]);
                    aposta.Bolao = Convert.ToInt32(idbolao);
                    aposta.Apostador = idUsuario;
                    _aposta.LancarPlacarJogo(aposta);
                }
                return RedirectToAction("ListarBoloesParticipante","Bolao");
            }
            catch(Exception ex)
            {
                return View();
            }
        }
        
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion post
    }
}

BetBolao/Controllers/BolaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BetBolao.Compartilhado.Dao;
using BetBolao.Compartilhado.Models;
using BetBolao.Dao;
using BetBolao.Models;
using BetBolao.ViewModel;

namespace BetBolao.Controllers
{
    [Authorize]
    public class BolaoController : Controller
    {
        #region Variables
        private readonly Competicao _competicao = new Competicao();
        private readonly List<Competicao> _competicoes = new List<Competicao>();
        //private readonly List<DTOParticipantesBolao> _convites = new List<DtoConvitesPendentes>();
        private readonly DaoBolao _dao = new DaoBolao();
        private readonly DaoConvite _daoConvite = new DaoConvite();
        private readonly Bolao _bolao = new Bolao();
        private readonly List<Bolao> _boloes = new List<Bolao>();
        private readonly Usuarios _usuarios = new Usuarios();
        private readonly ConvitesBolao _convite = new ConvitesBolao();
        #endregion

        #region métodos GET
        // GET: Bolao
        public ActionResult CadastrarBolao()
        {
            ViewBag.idUsuario = (int)Session["id"];
            ViewBag.competicoes = _competicao.TranformaListaCompeticoesEmSelectList(_competicao.ListarCompeticoes(new List<Competicao>()));
            //ViewBag.competicoes =  TranformaListaCompeticoesEmSelectList(ViewBag.competicoes);
            return View();
        }
        public ActionResult ListarBoloesParticipante()
        {
            _boloes.AddRange(_bolao.SelecinarBoloesPartipantes((int)Session["id"]));
            //_boloes.AddRange(_dao.ListarBoloesParticipante((int)Session["id"]));
            return View(_boloes);

        }
        public ActionResult CadastrarApostas(int id)
        {
            ViewBag.id = id;
            return View(new JogosCompeticao().ListaJogosCompeticao(id));
        }
        public ActionResult ConvidarParticipantes(int idbolao, int idanfitriao)
        {
            var auth = new AutenticacaoSeguranca();
            if (auth.PermissaoAcessoConfidencialConvidarAmigos(idanfitriao, idbolao))
            {
                return View();
            }
            return View("_NaoAutorizado");
        }
        public ActionResult ConvitesPendentes()
        {
            var id = (int)@Session["id"];

            var _convites = new List<DtoConvitesPendentes>();
            _convites.AddRange(_convite.RetornarConvitesPorUsuariosId(id));
            return View(_convites);

        }
        public ActionResult AceitarConvite(int id)
        {
            _convite.AceitarConvite(id);
            return RedirectToAction("ConvitesPendentes");
        }
        public ActionResult RejeitarConvite(int id)
        {
            _convite.RejeitarConvite(id);
            return RedirectToAction("ConvitesPendentes");

        }
        public ActionResult SairBolao(int idbolao)
        {
            var idusuario = Convert.ToInt32(Session["id"].ToString());
            _bolao.SairBolao(idbolao, idusuario);
            return RedirectToAction("ListarBoloesParticipante");

        }

        public ActionResult ListarBolao(int id)
        {
            var autenticacao = new AutenticacaoSeguranca();
            var idUsuario = (int)Session["id"];
            if (autenticacao.PermissaoAcessoConfidencialBolao(idUsuario, id))
            {
                var participantesBolao = new ParticipantesBolao();
                return View(participantesBolao.ListarBoloesParticipantes(id));
            }
            return View("_NaoAutorizado");
        }

        #endregion

        #region métodos Post
        [HttpPost]
        public ActionResult CadastrarBolao(Bolao bolao)
        {
            if (ModelState.IsValid)
            {
                bolao.CadastrarBolao(bolao);
            }
            return RedirectToAction("ListarBoloesParticipante", bolao.UsuarioCriadorBolao);
        }

        [HttpPost]
        public ActionResult ConvidarParticipantes(ConvitesBolao convitesBolao)
        {
            if (ModelState.IsValid)
            {
                var daoUsuarios = new DaoUsuarios();
                if ((convitesBolao.IdConvidado = daoUsuarios.RetornarIdUsuarioPorEmail(convitesBolao.EmailConvidado)) !=
                    0)
                {
                    _daoConvite.CriarConvite(convitesBolao);

                    return RedirectToAction("ConvidarParticipantes", new { idbolao = convitesBolao.IdBolao, idanfitriao = convitesBolao.IdAnfitriao });
                }
                TempData["mensagem"] = ViewBag.mensagem = "O email informado não é correspondente a um usuário do sistema";
            }
            return View();
        }

        #endregion

        #region métodos private

        #endregion
    }
}

BetBolao/Views/Bolao/CadastrarBolao.cshtml
@model BetBolao.Models.Bolao

@{
    ViewBag.Title = "CriarBolao";
}

<h2>Crie seu bolão...</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeBolao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeBolao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeBolao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">


            @Html.HiddenFor(model => model.UsuarioCriadorBolao, new { @Value = ViewBag.idUsuario })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCampeonatoAssociado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdCampeonatoAssociado, ViewBag.competicoes as SelectList, "selecione um campeonato", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCampeonatoAssociado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar Bolão" class="btn btn-default" />
                @Html.ActionLink("Cancelar", "HomeUsuario", "Home", null, new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
}
<div class="logo-area-usuario">
    <img src="~/Imagens/Área do bolão.png" />
</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BetBolao/Views/Bolao/ConvidarParticipantes.cshtml
@model BetBolao.Models.ConvitesBolao

@{
    ViewBag.Title = "ConvidarParticipantes";
}

<h2>Convidar amigos...</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @TempData["mensagem"]
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.IdConvite, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IdConvite, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdConvite, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @*@Html.LabelFor(model => model.IdBolao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IdBolao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdBolao, "", new { @class = "text-danger" })
                </div>*@
            @Html.HiddenFor(model => model.IdBolao)
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.IdAnfitriao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IdAnfitriao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdAnfitriao, "", new { @class = "text-danger" })
                </div>*@
            @Html.HiddenFor(model => model.IdAnfitriao)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailConvidado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmailConvidado, new { @class = "form-control"})
               
                @Html.ValidationMessageFor(model => model.EmailConvidado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TextoConvite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TextoConvite, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.TextoConvite, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.aberto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.aberto, new {@Value = "sim" } )
                    @Html.ValidationMessageFor(model => model.aberto, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.aceite, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.aceite, new { @Value = "não"})
                    @Html.ValidationMessageFor(model => model.aceite, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BetBolao/Views/Bolao/ConvitesPendentes.cshtml
@model IEnumerable<BetBolao.ViewModel.DtoConvitesPendentes>

@{
    ViewBag.Title = "ConvitesPendentes";
}

<h2>Convites Pendentes</h2>

@*@Html.ActionLink("Cadastrar Novo", "ConvidarParticipantes", null, new { @class = "btn btn-success" })*@
@Html.ActionLink("Voltar Home", "HomeUsuario", "Home", null, new { @class = "btn btn-info" })
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.IdBolao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeBolao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeAnfitriao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAnfitriao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeConvidado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailConvidado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TextoConvite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aberto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aceite)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.IdBolao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeBolao)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.NomeAnfitriao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAnfitriao)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.NomeConvidado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailConvidado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TextoConvite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Aberto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Aceite)
        </td>
        <td>
            @if (item.Aberto == "sim")
            {
                @Html.ActionLink("Aceitar", "AceitarConvite", new { id = item.IdConvite })
                <b>|</b>
                @Html.ActionLink("Rejeitar", "RejeitarConvite", new { id = item.IdConvite })
            }
            
        </td>
    </tr>
}

</table>

BetBolao/Views/Bolao/ListarBolao.cshtml
@model IEnumerable<BetBolao.ViewModel.DTOParticipantesBolao>

@{
    ViewBag.Title = "ListarBolao";
}

<h2>ListarBolao</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdBolao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeBolao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdUsuarioCriador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeCriador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdParticipante)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeParticipante)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pontuacao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdBolao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeBolao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdUsuarioCriador)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeCriador)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdParticipante)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeParticipante)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pontuacao)
        </td>
        <td>
        </td>
    </tr>
}

</table>

BetBolao/Views/Bolao/ListarBoloesParticipante.cshtml
@model IEnumerable<BetBolao.Models.Bolao>

@{
    ViewBag.Title = "ListarBoloesParticipante";
}

<h2>Bolões que você participa...</h2>
@Html.ActionLink("Cadastrar Novo", "CadastrarBolao", null, new { @class = "btn btn-success" })
@Html.ActionLink("Voltar Home", "HomeUsuario", "Home", null, new { @class = "btn btn-info" })
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeBolao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UsuarioCriadorBolao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdCampeonatoAssociado)
        </th>
        <th>
            @Html.Label("Opções")
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeBolao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UsuarioCriadorBolao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdCampeonatoAssociado)
        </td>
        <td>
            @if (item.UsuarioCriadorBolao == (int)Session["id"])
            {
                @Html.ActionLink("Convidar Amigos", "ConvidarParticipantes", new { idbolao = item.Id, idanfitriao = item.UsuarioCriadorBolao })
            }

            @Html.ActionLink("Visualizar Bolão","ListarBolao", "Bolao", new { id = item.Id}, null)
            @Html.ActionLink("Realizar Apostas","Apostar", "Apostas", new { idCompeticao = item.IdCampeonatoAssociado, idbolao = item.Id},null) |
            @Html.ActionLink("Sair Bolão", "SairBolao", new { idbolao = item.Id})



            @*@Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
        </td>

    </tr>
}

</table>

BetBolao/Views/Bolao/old_ConvitesPendentes.cshtml
@model IEnumerable<BetBolao.Models.ConvitesBolao>

@{
    ViewBag.Title = "ConvitesPendentes";
}

<h2>ConvitesPendentes</h2>

@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdConvite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdBolao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdAnfitriao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdConvidado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailConvidado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TextoConvite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aberto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aceite)
            </th>
            <th>
                Opção
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdConvite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdBolao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdAnfitriao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdConvidado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailConvidado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TextoConvite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Aberto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Aceite)
                </td>
                <td>
                    @if (item.Aberto == "sim")
                    {
                        @Html.ActionLink("Aceitar", "AceitarConvite", new {id = item.IdConvite})
                        <b>|</b>
                        @Html.ActionLink("Rejeitar", "RejeitarConvite", new {id = item.IdConvite})
                    }
                    else
                    {
                        <div>N/A</div>
                    }
                </td>
            </tr>
        }

    </table>
}
else
{
    <div> Você não possui convites pendentes</div>
}