BetBolao/Controllers/BolaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BetBolao.Compartilhado.Dao;
using BetBolao.Compartilhado.Models;
using BetBolao.Dao;
using BetBolao.Models;
using BetBolao.ViewModel;

namespace BetBolao.Controllers
{
    [Authorize]
    public class BolaoController : Controller
    {
        #region Variables
        private readonly Competicao _competicao = new Competicao();
        private readonly List<Competicao> _competicoes = new List<Competicao>();
        //private readonly List<DTOParticipantesBolao> _convites = new List<DtoConvitesPendentes>();
        private readonly DaoBolao _dao = new DaoBolao();
        private readonly DaoConvite _daoConvite = new DaoConvite();
        private readonly Bolao _bolao = new Bolao();
        private readonly List<Bolao> _boloes = new List<Bolao>();
        private readonly Usuarios _usuarios = new Usuarios();
        private readonly ConvitesBolao _convite = new ConvitesBolao();
        #endregion

        #region métodos GET
        // GET: Bolao
        public ActionResult CadastrarBolao()
        {
            ViewBag.idUsuario = (int)Session["id"];
            ViewBag.competicoes = _competicao.TranformaListaCompeticoesEmSelectList(_competicao.ListarCompeticoes(new List<Competicao>()));
            //ViewBag.competicoes =  TranformaListaCompeticoesEmSelectList(ViewBag.competicoes);
            return View();
        }
        public ActionResult ListarBoloesParticipante()
        {
            _boloes.AddRange(_bolao.SelecinarBoloesPartipantes((int)Session["id"]));
            //_boloes.AddRange(_dao.ListarBoloesParticipante((int)Session["id"]));
            return View(_boloes);

        }
        public ActionResult CadastrarApostas(int id)
        {
            ViewBag.id = id;
            return View(new JogosCompeticao().ListaJogosCompeticao(id));
        }
        public ActionResult ConvidarParticipantes(int idbolao, int idanfitriao)
        {
            var auth = new AutenticacaoSeguranca();
            if (auth.PermissaoAcessoConfidencialConvidarAmigos(idanfitriao, idbolao))
            {
                return View();
            }
            return View("_NaoAutorizado");
        }
        public ActionResult ConvitesPendentes()
        {
            var id = (int)@Session["id"];

            var _convites = new List<DtoConvitesPendentes>();
            _convites.AddRange(_convite.RetornarConvitesPorUsuariosId(id));
            return View(_convites);

        }
        public ActionResult AceitarConvite(int id)
        {
            _convite.AceitarConvite(id);
            return RedirectToAction("ConvitesPendentes");
        }
        public ActionResult RejeitarConvite(int id)
        {
            _convite.RejeitarConvite(id);
            return RedirectToAction("ConvitesPendentes");

        }
        public ActionResult SairBolao(int idbolao)
        {
            var idusuario = Convert.ToInt32(Session["id"].ToString());
            _bolao.SairBolao(idbolao, idusuario);
            return RedirectToAction("ListarBoloesParticipante");

        }

        public ActionResult ListarBolao(int id)
        {
            var autenticacao = new AutenticacaoSeguranca();
            var idUsuario = (int)Session["id"];
            if (autenticacao.PermissaoAcessoConfidencialBolao(idUsuario, id))
            {
                var participantesBolao = new ParticipantesBolao();
                return View(participantesBolao.ListarBoloesParticipantes(id));
            }
            return View("_NaoAutorizado");
        }

        #endregion

        #region métodos Post
        [HttpPost]
        public ActionResult CadastrarBolao(Bolao bolao)
        {
            if (ModelState.IsValid)
            {
                bolao.CadastrarBolao(bolao);
            }
            return RedirectToAction("ListarBoloesParticipante", bolao.UsuarioCriadorBolao);
        }

        [HttpPost]
        public ActionResult ConvidarParticipantes(ConvitesBolao convitesBolao)
        {
            if (ModelState.IsValid)
            {
                var daoUsuarios = new DaoUsuarios();
                if ((convitesBolao.IdConvidado = daoUsuarios.RetornarIdUsuarioPorEmail(convitesBolao.EmailConvidado)) !=
                    0)
                {
                    _daoConvite.CriarConvite(convitesBolao);

                    return RedirectToAction("ConvidarParticipantes", new { idbolao = convitesBolao.IdBolao, idanfitriao = convitesBolao.IdAnfitriao });
                }
                TempData["mensagem"] = ViewBag.mensagem = "O email informado não é correspondente a um usuário do sistema";
            }
            return View();
        }

        #endregion

        #region métodos private

        #endregion
    }
}

BetBolao/Controllers/HomeController.cs
using System.Web.Mvc;

namespace BetBolao.Controllers
{
    
    public class HomeController : Controller
    {

        //System.Web.HttpContext.Current.Session["sessionString"] = sessionValue; 
        //// GET: Home
        //public ActionResult Index()
        //{
        //    return View();
        //}
        [AllowAnonymous]
        public ActionResult Home()
        {
            ViewBag.mensagem = this.Page_Load();
            ViewBag.nome = Session["Nome"] as string;
            return View(ViewBag);

        }

        protected string Page_Load()
        {
            var lblSessionID = string.Format(": {0}", Session["nome"]);
            //var lblSessionID = string.Format("Session id: {0}", Session.SessionID);
            return lblSessionID;
        }
        [Authorize]
        public ActionResult HomeAdministrativa()
        {
            return View();
        }

        //public ActionResult HomeUsuario()
        //{
        //    return View();
        //}

        [Authorize]
        public ActionResult HomeUsuario()
        {
            return View();
        }

        public ActionResult Login()
        {
            return ContextDependentView();
        }

        private ActionResult ContextDependentView()
        {
            string actionName = ControllerContext.RouteData.GetRequiredString("action");
            if (Request.QueryString["content"] != null)
            {
                ViewBag.FormAction = "Json" + actionName;
                return PartialView();
            }
            ViewBag.FormAction = actionName;
            return View();
        }
    }
}

BetBolao/Controllers/PaisesController.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;
using BetBolao.Models;

namespace BetBolao.Controllers
{
    [Authorize]
    public class PaisesController : Controller
    {
        #region variáveis
        // GET: Paises
        private static string _resultado;
        private static bool _habilitar;
        private readonly Pais _pais = new Pais();
        private readonly List<Time> _times = new List<Time>();
        #endregion

        #region get
        public ActionResult Index()
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                return RedirectToAction("ListarPaisesCadastrados");
            }
            return View("_NaoAutorizado");

        }

        public ActionResult CadastrarPais()
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                if (_habilitar)
                {
                    _habilitar = false;
                    return View();
                }
                else
                {
                    _resultado = "";
                    return View();
                }
            }
            return View("_NaoAutorizado");
        }


        [DisplayName("Listar Países")]
        public ActionResult ListarPaisesCadastrados()
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                var dao = new DaoPaises();
                var paises = new List<Pais>();
                //paises.AddRange(dao.paisesCadastrados());
                paises.InsertRange(0, dao.SelecionarPaisesCadastrados());
                return View(paises);
            }
            return View("_NaoAutorizado");
        }

        public ActionResult EditarPais(int id)
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                if (_habilitar)
                {
                    _habilitar = false;
                }
                else
                {
                    _resultado = "";
                }
                var dao = new DaoPaises();
                var pais = new Pais();
                pais = dao.SelecionarPaisPorId(id);
                return View(pais);
            }
            return View("_NaoAutorizado");
        }


        public ActionResult DetalharPais(int id)
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                ViewBag.abreviacao = _pais.RetornaAbreviacaoPais(id);
                ViewBag.nomePais = _pais.RetornaNomePais(id);
                return View(_pais.RetornarTimesPorPais(_times, id));
            }
            return View("_NaoAutorizado");
        }

        #endregion
        #region métodos post
        [HttpPost]
        public ActionResult editarPais(Pais pais)
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                var dao = new DaoPaises();
                if (ModelState.IsValid)
                {
                    var _pais = new Pais();
                    _pais = dao.SelecionarPaisPorId(pais.IdPais);

                    if ((_pais.NomePais == pais.NomePais.ToUpper()) & (_pais.Abreviacao == pais.Abreviacao.ToUpper()))
                    {
                        ModelState.AddModelError("",
                            "Os dados não foram alterados, pois você não alterou nenhum dado deste país!");
                    }
                    else
                    {
                        if (dao.verificarPaisJaCadastrado(pais.NomePais, pais.IdPais))
                        {
                            ModelState.AddModelError("",
                                "Os dados não puderam ser alterado pois já existe um país com o mesmo nome!");
                        }
                        else
                        {
                            dao.AtualizarPais(pais);
                            return RedirectToAction("ListarPaisesCadastrados");
                        }
                    }
                }
                return View(pais);
            }
            return View("_NaoAutorizado");
        }

        [HttpPost]
        public ActionResult CadastrarPais(Pais pais)
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {

                var dao = new DaoPaises();
                if (ModelState.IsValid)
                {
                    string resultado = dao.CadastrarPais(pais);
                    PaisesController._resultado = resultado;
                    TempData["mensagem"] = PaisesController._resultado;
                    _habilitar = true;
                    return RedirectToAction("CadastrarPais");

                }
                return View();
            }
            return View("_NaoAutorizado");
        }

        #endregion

    }
}

BetBolao/Controllers/TimesController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using BetBolao.Compartilhado.Dao;
using BetBolao.Models;

namespace BetBolao.Controllers
{
    [Authorize]
    public class TimesController : Controller
    {
        #region Private Variables
        private static string _resultado;
        private DaoTimes _dao = new DaoTimes();
        private List<Pais> _paises = new List<Pais>();
        private List<Time> _times = new List<Time>();
        private Time _time = new Time();

        #endregion


        // GET: Times
        #region Métodos GET Public
        public ActionResult Index()
        {
            var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                return RedirectToAction("ListarTodosOsTimes");
            }
            return View("_NaoAutorizado");
        }

        public ActionResult CadastrarTime()
        {var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                ViewBag.IdPais = CarregaTodosPaises();
                if (TempData["mensagem"] is Nullable)
                {
                    var mensagem = TempData["mensagem"] as string;
                }

                return View();
            }
            return View("_NaoAutorizado");
        }


        public ActionResult ListarTodosOsTimes()
        {var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                if (TempData["mensagem"] is Nullable)
                {
                    var mensagem = TempData["mensagem"] as string;
                }
                var time = new Time();
                time.RetornaTimes(_times);
                return View(_times);
            }
            return View("_NaoAutorizado");
        }

        public ActionResult EditarTime(int id)
        {var idusuario = (int)Session["id"];
            var auth = new AutenticacaoSeguranca();
            if (!auth.PermissaoAcessoUsuarioApostador(idusuario))
            {
                var time = new Time();
                return View(time.RetornaTime(id));
            }
            return View("_NaoAutorizado");
        }

        #endregion


        #region Médotos Post Public
        [HttpPost]
        public ActionResult CadastrarTime(Time time)
        {
            if (ModelState.IsValid)
            {
                string resultado = _dao.CadastrarTime(time);
                TimesController._resultado = resultado;
                TempData["mensagem"] = TimesController._resultado;
                return RedirectToAction("CadastrarTime");
            }
            return View();
        }
        [HttpPost]
        public ActionResult EditarTime(Time time)
        {
            if (ModelState.IsValid)
            {
                TempData["mensagem"] = _dao.AtualizarTime(time);
            }
            return RedirectToAction("ListarTodosOsTimes");
        }
        #endregion

        #region Métodos Privados
        private SelectList CarregaTodosPaises()
        {
            return new SelectList(
                      new Pais().RetornarPaises(_paises)
                //,"nomePais"
                      , "idPais"
                      , "nomePais"
                      );
        }


        #endregion
    }


}

BetBolao/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Home</h2>
teste:
@ViewBag.mensagem


<div class="alinhamentoLeft">
    <b class="">
        esta div terá informações para se cadastrar ou logar no sistema de bolão
    
    </b><br><br><br>
    Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.

    <br>
    <br>
    <br>
    <a href="/Usuarios/Participar" class="">Cadastrar</a>
    <br>
    <a href="/Conta/LogOn" class="">Logar</a>
    <br>

    <a href="/Home/HomeUsuario" class="">Home</a>
</div>

<div class="alinhamentoRight">
    <b>esta div terá informações à respeito do bolão. </b><br />
    <br />
    <br/>
    Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.
    <br />
    <br/>
    teste
    <br />
    
    @Session["Nome"]
    @Session["email"]
    @Session["senha"]
    @Session["id"]
    @Session["dataNascimento"]
    @Session["comentarios"]
    @Session["timeFavorito"]
    @Session["perfil"]
    
</div>

BetBolao/Views/Home/HomeAdministrativa.cshtml
@{
    ViewBag.Title = "Home Administrativa";
}

<h2>Dashboard - Administrativo</h2>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-info">
                <h4 class="panel panel-heading">Área de Usuário</h4>
                <div class="btn">
                    @Html.ActionLink("Alterar cadastro", "Editar", "Usuarios", null, new {@class = "btn btn-success "})
                </div>
                <div class="btn">
                    @Html.ActionLink("Cadastrar novo Apostador", "Participar", "Usuarios", null, new { @class = "btn btn-success " })
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="panel panel-info">
                <h4 class="panel panel-heading">Área de Países</h4>
                <div class="btn">
                    @Html.ActionLink("Cadastrar País", "CadastrarPais", "Paises", null, new {@class = "btn btn-success"})
                </div>
                <div class="btn">
                    @Html.ActionLink("Listar Países", "ListarPaisesCadastrados", "Paises", null, new {@class = "btn btn-success"})
                </div>
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-info">
                <h4 class="panel panel-heading">Área de Competições</h4>
                <div class="btn">
                    @Html.ActionLink("Cadastrar Competição", "CadastrarCompeticao", "Competicao", null, new {@class = "btn btn-success"})

                </div>
                <div class="btn">
                    @Html.ActionLink("Listar Competicões", "ListarCompeticoes", "Competicao", null, new {@class = "btn btn-success"})
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="panel panel-info">
                <h4 class="panel panel-heading">Área de Times</h4>
                <div class="btn">
                    @Html.ActionLink("Cadastrar Times", "CadastrarTime", "Times", null, new { @class = "btn btn-success" })

                </div>
                <div class="btn">
                    @Html.ActionLink("Listar Times", "Index", "Times", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>

        
    </div>
</div>

BetBolao/Views/Home/HomeUsuario.cshtml
@{
    ViewBag.Title = "HomeUsuario";
}

<h2>
    Dashboard - Usuário
</h2>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-info">
                <h4 class="active panel-heading">Área de Usuário</h4>
                <div class="btn">
                    @Html.ActionLink("Editar Cadastro", "Editar", "Usuarios", null, new { @class = "btn btn-success " })
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-info">
                <h4 class="panel panel-heading">Área de Bolão</h4>
                <div class="btn">
                    @Html.ActionLink("Cadastrar Bolão", "CadastrarBolao", "Bolao", null, new { @class = "btn btn-success" })
                </div>
                <div class="btn">
                    @Html.ActionLink("Convites Pendentes", "ConvitesPendentes", "Bolao", null, new { @class = "btn btn-success" })
                </div>
                <div class="btn">
                    @Html.ActionLink("Listar Bolões Participante", "ListarBoloesParticipante", "Bolao", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-info">
                <h4 class="panel panel-heading">Área de Competições</h4>
                @*<div class="btn">
                        @Html.ActionLink("Cadastrar Competição", "CadastrarCompeticao", "Competicao", null, new { @class = "btn btn-success" })

                    </div>*@
                <div class="btn">
                    @Html.ActionLink("Listar Competicões Cadastradas", "ListarCompeticoes", "Competicao", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-danger">
                <h4 class="panel panel-heading">Lembretes</h4>
                <div>
                    <span>Nesta área, a ideia seria mostrar ao apostador a quantidade de jogos que acontecerão nos próximos 7 dias baseando-se nas competições em que ele está participando pelos bolões.</span>
                    @*@Html.ActionLink("Modelo Exemplo", "", "", null, new { @class = "btn btn-danger" })*@
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-danger">
                <h4 class="panel panel-heading">Jogos</h4>
                <span>
                    Nesta área, a ideia seria mostrar opções em relação aos jogos finalizados na última semana de acordo com os bolões que ele participa.
                </span>
            </div>
        </div>

        <div class="col-sm-4">
            <span class="panel panel-danger">
                <h4 class="panel panel-heading">Ranking</h4>
                <span>
                    nesta área, a ideia seria mostrar um dashboard do usuário apontando quantos palpites ele acertou, quantos pontos ele obteve no mês, a média de pontos dele por jogo, variação do desempenho dele em relação aos seus amigos de bolão.
                </span>
            </span>
        </div>
    </div>
</div>

BetBolao/Views/Home/Index.cshtml
klj